language: ruby
rvm:
- 2.6.9
- 2.7.5
- 3.0.3
cache: bundler
env:
  matrix:
    - TEST_RAILS_VERSION=6.1
    - TEST_RAILS_VERSION=6.0
addons:
  postgresql: '10'
after_script: bundle exec codeclimate-test-reporter
