language: ruby
rvm:
- 2.6.9
- 2.7.5
- 3.0.3
cache: bundler
gemfile:
  - gemfiles/activesupport_6.0.gemfile
  - gemfiles/activesupport_6.1.gemfile
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '10'
after_script: bundle exec codeclimate-test-reporter
