language: ruby
rvm:
- 2.5.8
- 2.6.6
- 2.7.2
- 3.0.0
cache: bundler
gemfile:
  - gemfiles/activesupport_6.0.gemfile
  - gemfiles/activesupport_6.1.gemfile
env:
  global:
  - RUBY_GC_HEAP_GROWTH_MAX_SLOTS=300000
  - RUBY_GC_HEAP_INIT_SLOTS=600000
  - RUBY_GC_HEAP_GROWTH_FACTOR=1.25
addons:
  postgresql: '10'
after_script: bundle exec codeclimate-test-reporter
